configuration: Release
image: Visual Studio 2017
platform: x64

build_script:
- git submodule update --init --recursive
- mkdir build
- cd build 
- cmake -T host=x64 -G "Visual Studio 15 2017" -A x64 -DCMAKE_PREFIX_PATH=C:\Qt\5.13.0\msvc2017_64 ..
- cmake --build . --config Release --target Package

