configuration: Release
image: Visual Studio 2019 Preview
platform: x64

build_script:
- git submodule update --init --recursive
- mkdir build
- cd build 
- cmake -T host=x64 -G "Visual Studio 16 2019" -A x64 ..
- cmake --build . --config Release --target Package

